const DEFAULT_OPTIONS = {
  title: 'title测试1git',
  fullContent: 'fullcontent测试1git',
  fullIcon: '',
  fullIconColor: '',
  fullStyle: 'good',
  onlyOriginalContent: 'only测试1git',
  onlyOriginalIcon: '',
  onlyOriginalIconColor: '',
  onlyOriginalStyle: 'info',
  notAvailableContent: 'notav测试1git',
  notAvailableIcon: '',
  notAvailableIconColor: '',
  notAvailableStyle: 'alert',
  errorContent: '测试1git',
  errorIcon: '',
  errorIconColor: '',
  errorStyle: 'error',
}
